### ISSUE TITLE
Write error: line 181

### ISSUE THREAD

**Issue by ShadowFlareon** [finlandhl/kali-ios#4]
Idk why this happens please fix this

**Comment by finlandhl** [comment]
Hello, can you better explain your issue, thanks

**Comment by ShadowFlareon** [comment]
So i do the importing, and halfway through it says “write errorr: line 181”

**Comment by ShadowFlareon** [comment]
It appears to be something to do with john, as it happens while installing john

**Comment by ShadowFlareon** [comment]
Ok: So, when I am importing the files, when it is importing a JTR package, it suddenly stops and says "Write error: Line 181" Maybe there is a package problem? I tried many times and it always happens while installing JTR. I am using an iPadOS 16.5(maybe that's the issue but idk), and have 3.8 GB available, just to make sure its not a storage issue

**Comment by finlandhl** [comment]
Try freeing up your iPad storage and try again.

**Comment by ShadowFlareon** [comment]
Ok sire

**Comment by ShadowFlareon** [comment]
Again, but this time, when the blue line was like 99% there, the error appeared. Whywhywhy

**Comment by ShadowFlareon** [comment]
It worked, but after booting, the app just crashes and I cant open it

**Comment by ShadowFlareon** [comment]
Wait no im making a new issue
