### ISSUE TITLE
the new download files ?

### ISSUE THREAD

**Issue by qasimkhn** [finlandhl/kali-ios#9]
the new download file looks exactly the same like previous one?is it new or same?

**Comment by finlandhl** [comment]
Sorry, fixed now with the new file

**Comment by finlandhl** [comment]
Sorry, everything should be ok from now. Informations and download links are included in the text file ‘kali-ios_v1.1.0.text’ from the release tag. 
Just download it and copy the link inside

**Comment by qasimkhn** [comment]
thanks working fine now
